### PR TITLE
Transient

### PR DESCRIPTION
**Pull request by GZingaro**
## Anything Else? getK_elastic inputs were modified for the functions handles to continue working for the assembly of the NR system of equations.

### CODE REVIEW

**Comment by GZingaro** [comment]
Uploaded modified files.

**Review by SaeedHatefi — CHANGES_REQUESTED** [review]
- [x] Reviewed function(s): RunSim, RunTest, main_nonlinear, getK_transient, PlateWithHoleTransient
- [x] Ran test case(s): RunSim, RunTests: ! Failure in all tests. Needed to update all the config files
* Purpose of the code: 
   - To add a transient analysis
* Notes on implementation: 
   - It would be better to create a test case for transient analysis and put the config file "PlateWithHoleTransient.m" into its corresponding config file instead of putting it in the main config files folder.
   - Please define control.transient in all config files (+ test cases) in the section Computation controls
   - Please define control.alpha in all config files (+ test cases) in the section Computation controls
   - In the config file "PlateWithHoleTransient.m", there are two sections of "Material Properties (Solid)". Please remove one of them.
   - Please create some comments for transient toggle. For instance, 0: static, 1: transient ,...
   - In the case that we don't want to consider transient behavior, there is an error in code. It seems we need to initialize damping stiffness matrix. By this way, in the case without transient effect, C is a zero matrix.
   - I have also reviewed the algorithm of transient case + Newton-Raphson loop. I have some comments to discuss:
         - Please consider updating dnm1 and dnm2 inside the Newton-Raphson loop
         - Please apply BC on \DeltaU. Especially, when U is a fucntion of time
         - Inside of the function stiffness matrix: Please double check the formulation for Fext. If we consider alpha=1, Fext is not correct.
    - I think getK_elastic can be the same with getK_transient. I am thinking that finally we will have just one transient code which is working for static cases.
* Notes on legibility and style: N/A
* Notes on maintainability: N/A
* Suggested test cases: 
   * The current test case is for time-dependent essential BC. I would suggest considering the case where Fext is a function of time.

**Comment by GZingaro** [comment]
Thank you, Saeed. Comments have been addressed. Please review Test 27 in Run_test.

**Review by SaeedHatefi — CHANGES_REQUESTED** [review]
- [x] Reviewed function(s): RunSim, RunTest, main_nonlinear, RunTransientTest, TransientTest, MasterConfigFile, Transient1D_check
- [x] Ran test case(s): RunTests, RunTransientTest

* Purpose of the code: To add a transient analysis
* Notes on implementation:
   - It would be better to put control.alpha in the section for transient control in config files. It is already in the section related to Newton Raphson controls. 
   - The file "PlateWithHoleTransient.m" can be deleted if you are adding a test file for transient.
   - My suggested name for config file for transient test is "ManufacturedSolution_Transient" other than "TransientTest".
   - The discerption for the the test file (RunTransientTest) can be modified to explain manufactured solution for transient case.
   - In the config file, it seems that MeshType should be "GMSH". When MeshType is selected as GMSH, there is an error in running the code. I think first, this error should be improved then I can check the results of manufactured solution.
* Notes on legibility and style: N/A
* Notes on maintainability: N/A

**Comment by SaeedHatefi** [comment]
I have just one comment. The tolerance is 0.1 in the test case and the error is about 0.03. The test is passed but the error is somehow big.

**Review by SaeedHatefi — APPROVED** [review]

**Pull request merged**
