### PR TITLE
Thermal

### PR DESCRIPTION
**Pull request by b3gee**
## What?
Add the ability to analyze diffusion problems to the code. The code now supports steady-state, transient, isotropic, and orthotropic material models.
## Why?
To solve diffusion problems like temperature or porous media flow.
## How?
A new material model for diffusion was added to the code. Changes were made throughout the code to de-couple the assumption that the number of degrees of freedom were tied to the number of space dimensions.
## Testing?
RunTests works with the new framework. A new test case was added based on [Analytical Solution B](https://github.com/GCMLab/GCMLab-FEM/wiki/Analytical-Solution-B) . 
## Anything Else?
Currently the transient case is determined by a switch in the config file same as the transient elastic case. This should perhaps be separated into 2 material models sometime in the future.

### CODE REVIEW

**Review by SaeedHatefi — CHANGES_REQUESTED** [review]
- [x] Reviewed function(s): RunSim, RunTests, ThermalConfigFile, main_nonlinear, cleanInput, getK_TH1, getFlux_TH1, getK_dfsn, write2vtk_dfsn, getD_TH1, RunDiffusionTest, Diffusion_check, DiffusionTest
- [x] Ran test case(s): RunSim, RunTests
* Purpose of the code: To add diffusion problem to the code
* Notes on implementation:  The code works well for thermal and equilibrium problems. However, there are some suggestions to make the code more clear for the user:
   *  The current version of thermal code is for transient type of problem. So, we can classify the thermal problem as transient case not static case in the implementation. 
   * The other suggestion is that we can consider different alpha for thermal problem (e.g. Crank-Nicolson).
* Notes on legibility and style:
   * In the test case 29, a transient thermal case is solved. If I am correct, please modify the explanations for this test case into thermal transient test case
   * Consider that the user tries to solve a diffusion problem. In this case, control.transient should be zero or 1? Some explanations can be defined in config file regarding this issue to avoid any confusion about transient parameter for thermal and equilibrium problems.
   * The format of getC function for thermal case is the same with transient deformation case. However, I will suggest to add some explanations in the header function for getC to explain that this function is for the calculation of damping matrix and conductivity matrix.
   * In main_nonlinear function, when we are calculating C, we can add some comments regarding C which is related to equilibrium case or thermal case. One other option is the definition of Material.ProblemType when we are calling getC function in main_nonlinear.
   * I will suggest to modify progress messages according to the cases we are solving. For example, in the current version of the code, it is just showing "Assembling Linear Elastic Stiffness Matrix..." for both equilibrium and thermal cases. It would be nice if these types of messages are fitted with the problem type.
   * In cleanInput function, I suggest to consider some controllers for positive and negative thermal coefficients (conductivity and heat capacity). 
* Notes on maintainability: N/A
* Suggested test cases: N/A

**Comment by b3gee** [comment]
- The transient and steady-state diffusion problems have been separated into 2 material models, rather than relying on the Control.transient toggle. 
- The code works for both Backwards Euler and Crank-Nicolson with alpha = 1 and alpha = 0.5 respectively. The rate of convergence of these two methods has not yet been verified.

- Test case 29 is a steady-state diffusion problem. A transient diffusion test case is recommended for future implementation.
- Control.transient has been superseded by separating the material models.
- The header of getC has been updated to reflect the fact that the same code is used for the transient elastic and transient thermal cases, specifying how the parameter Material.C is either the damping coefficient or the heat capacity.
- Progress messages have been updated for different problem cases
- cleanInput has been updated to include diffusion parameters.

**Review by SaeedHatefi — CHANGES_REQUESTED** [review]
- [x] Reviewed function(s): RunSim, RunTests, ThermalConfigFile, main_nonlinear, cleanInput, getK_TH1, getFlux_TH1, getK_dfsn, write2vtk_dfsn, getD_TH1, RunDiffusionTest, Diffusion_check, DiffusionTest
- [x] Ran test case(s): RunSim, RunTests
* Purpose of the code: To add diffusion problem to the code
* Notes on implementation:  All the concerns have been correctly addressed in the response. However, there are still some issues required to be addressed before approving the branch: 
   * Consider that Config files in the folder "Config Files" are consistent with all the updates related to the material set. There are some bugs when it is tried to run some of config files using RunSim, e.g., NLElastic_1DBar, NLElastic_2DPlate, PlateWithHole.
   * Consider three different status of stress calculation for thermal problem. The code is correctly working for nodal case but there is a bug for L2projection and center cases.
* Notes on legibility and style: N/A
* Notes on maintainability: N/A
* Suggested test cases: N/A

**Comment by b3gee** [comment]
- The existing config files have been updated to run on the new config file format.
- The bugs in the flux calculations have been fixed.

**Review by SaeedHatefi — APPROVED** [review]

**Pull request merged**
