### PR TITLE
Patch test

### PR DESCRIPTION
**Pull request by shatefia**
The PatchTest branch is now ready to merged back to the develop branch, but it is first awaiting a code review.

### CODE REVIEW

**Comment by b3gee** [comment]
The patch tests look good to test the behaviour of the FEM method in the x-direction. 

I suggest the following the changes:
- Patch Test A doesn't test very much since all DoFs are prescribed. I suggest removing it.
- Patch Test B and C are good as they allow us to test Dirichlet-Dirichlet and Dirichlet-Neumann BC combinations. I suggest prescribing the same displacements and forces that are applied on the right edge to the top edge, so that we can test for issues in both the x-direction and y-direction simultaneously.

**Comment by shatefia** [comment]
Patch Test A tests shape functions and standard order quadrature.

Yes, your suggestion is very good to test the code for issues in both directions. I will create Patch Test D to consider this.

**Comment by endrinar** [comment]
I agree with Saeed that Patch Test A is also worth having. Ensuring that the residuals are zero is a good way to make sure that stiffness matrix calculation is accurate.

**Comment by endrinar** [comment]
I also suggest using values for the domain lengths that are not 1m. Perhaps change the value of Young's modulus too to a number that adds more complexity, like 2230, for example.

**Comment by b3gee** [comment]
The changes requested in this branch have been implemented in the Automate-Testing branch. This branch can now be closed and deleted.

**Pull request closed without merging**
