### PR TITLE
Sanitize input

### PR DESCRIPTION
**Pull request by nbetan**
## What? 
Checks for bad input and notifies user of warnings/errors
## Why?
To catch errors
## How?
New functions to evaluate correctness of input file
## Testing?
Tried wrong inputs and received correct warnings/errors 
No specific testing function for this branch
## Anything Else?
The latest commit also includes the merge from the develop

### CODE REVIEW

**Review by SaeedHatefi — CHANGES_REQUESTED** [review]
- [x] Reviewed function(s): setDefaults, cleanInput, getD, getK, getStrain, main
- [x] Ran test case(s): PatchTestA, PlateWHole
* Purpose of the code: to check the code for bad input and notify the user of warnings and errors
* Notes on implementation: I modified two small bugs in cleanInput function. I tested the code for different bad inputs and it looks good when E and nu are constant.
    - Consider the point that E or nu is not constant and is the function of X
* Notes on legibility and style: N/A
* Notes on maintainability: N/A
* Suggested test cases: 
  - I suggest trying to run one of the tests (e.g. PatchTestA) in the case that E or nu is not constant and is the function of X. By this way, it is easy to check if the code works well for this case when the amount of E or nu is invalid in some gauss points.

**Comment by nbetan** [comment]
> * [x]  Reviewed function(s): setDefaults, cleanInput, getD, getK, getStrain, main
> * [x]  Ran test case(s): PatchTestA, PlateWHole
> 
> * Purpose of the code: to check the code for bad input and notify the user of warnings and errors
> * Notes on implementation: I modified two small bugs in cleanInput function. I tested the code for different bad inputs and it looks good when E and nu are constant.
>   
>   * Consider the point that E or nu is not constant and is the function of X
> * Notes on legibility and style: N/A
> * Notes on maintainability: N/A
> * Suggested test cases:
>   
>   * I suggest trying to run one of the tests (e.g. PatchTestA) in the case that E or nu is not constant and is the function of X. By this way, it is easy to check if the code works well for this case when the amount of E or nu is invalid in some gauss points.

I added some lines that evaluate the case when it is a function or a scalar

**Comment by nbetan** [comment]
@SaeedHatefi I made changes in the function cleanInput.m to account for cases where E and nu are constants or functions.

**Review by SaeedHatefi — APPROVED** [review]

**Comment by SaeedHatefi** [comment]
Looks good! I tested the code for different bad inputs and it works when E and nu are constant or functions. Also, I edited a typo in cleanInput function.

**Pull request merged**
