### PR TITLE
L2 stresses

### LINKED ISSUE #46: Stress recovery using L2 projection

### PR DESCRIPTION
**Pull request by b3gee**
L2-projection of stresses.

Contains test case of a plate with a hole under tension. L2 stresses should have a lower error compared to the analytical solution than the nodal average stresses. 

Test case adapted from OpenFOAM: https://www.openfoam.com/documentation/tutorial-guide/tutorialse9.php

### CODE REVIEW

**Review by endrinar — CHANGES_REQUESTED** [review]
- [x] Reviewed function(s): getStrain, PlateWithHole_check
- [x] Ran test case(s): RunT6_PlateWHole
* Purpose of the code: Compute nodal stresses using L2 projection
* Notes on implementation: 
   * The line `if ~strcmp(calc_type,'none')` removed all calculations of stresses at nodes. Consider maintaining this functionality (it should not be the default since it will not be output to VTK, but at least maintain it as an available option for debugging)
   * Consider looping through each dimension (defined in variable dim) to get each component of stress and strain. That way the code does not need to be hard-coded for 2D elements only.
   * In PlateWithHole_Check, why divide error norm by 2? (i.e.dL/2)
* Notes on legibility and style: 
   * Add the 'L2projection' option in the header of MasterConfigFile
* Notes on maintainability: 
   * Is there any way that we can make a function to perform the task of forming the vectorized stiffness matrix? I know that we have this code in at least two places (getK and getStrain) and it's not necessarily intuitive for the developers to read. If we make a function that takes as input the element matrix, A_e, and the vectors A, row, and col, it could output the updated A, row, and col vectors. In terms of readability it would make it more clear (reducing 10 lines of code to 1), but I'm not sure if this idea would just slow down performance having to pass more variables between functions. Thoughts? 
* Suggested test cases: 
   * I like the test case that you created. I will use this to create a tutorial for the Wiki before we incorporate this into the develop branch.

**Comment by b3gee** [comment]
>     * Notes on implementation:
>       
>       * The line `if ~strcmp(calc_type,'none')` removed all calculations of stresses at nodes. Consider maintaining this functionality (it should not be the default since it will not be output to VTK, but at least maintain it as an available option for debugging)

Previously, the stress calculation 'none' looped through all the elements and calculated stresses at all nodes in each element, then output none of them - which to me seems like a waste of computation power. Personally, I can't envision a situation in which I want to see the stress calculation for debugging, then not look at the plotted stress contours. My intuition as a user would be that 'none' prevents any stress calculations from taking place in order to increase the efficiency of the code. 

>       * Consider looping through each dimension (defined in variable dim) to get each component of stress and strain. That way the code does not need to be hard-coded for 2D elements only.

I wanted to avoid looping over dim so that I didn't re-calculate the stress at the same quadrature point 3 or 6 times. I have removed the 2D hard-coding by using tiered if-statements.

>       * In PlateWithHole_Check, why divide error norm by 2? (i.e.dL/2)

The term dL/2 is the Jacobian for 1D numerical integration.

> 
>     * Notes on legibility and style:
>       
>       * Add the 'L2projection' option in the header of MasterConfigFile

Done.

> 
>     * Notes on maintainability:
>       
>       * Is there any way that we can make a function to perform the task of forming the vectorized stiffness matrix? I know that we have this code in at least two places (getK and getStrain) and it's not necessarily intuitive for the developers to read. If we make a function that takes as input the element matrix, A_e, and the vectors A, row, and col, it could output the updated A, row, and col vectors. In terms of readability it would make it more clear (reducing 10 lines of code to 1), but I'm not sure if this idea would just slow down performance having to pass more variables between functions. Thoughts?

I agree that the vectorized stiffness matrix is not intuitive to read.  The vectorization also includes the initialization and forming the sparse matrix later on, so the function would only include a section of the vectorization procedure. I think we could explain though the function header the other requirements needed to operate the vectorization. Given that it is only 2 places at the moment, I don't think we need it yet - but as we continue to expand the code to other stiffness/conductivity/mass/ or capacity matrices, it could become useful. I suggest we open it as an issue for the time being.

**Comment by endrinar** [comment]
> > ```
> > * Notes on implementation:
> >   
> >   * The line `if ~strcmp(calc_type,'none')` removed all calculations of stresses at nodes. Consider maintaining this functionality (it should not be the default since it will not be output to VTK, but at least maintain it as an available option for debugging)
> > ```
> 
> Previously, the stress calculation 'none' looped through all the elements and calculated stresses at all nodes in each element, then output none of them - which to me seems like a waste of computation power. Personally, I can't envision a situation in which I want to see the stress calculation for debugging, then not look at the plotted stress contours. My intuition as a user would be that 'none' prevents any stress calculations from taking place in order to increase the efficiency of the code.
> 

I agree with what you're saying, so we're going to have to change the code a bit for this to make sense. Currently, the default output for getStrain is not of value, so I propose we make the default option 'center' (most efficient). We will need to change the header for getStrain and check setDefaults.m. Also in getStrain, change the default given if nargin < 4. 

Then, I suggest we add an if statement at the start of getStrain. If calc_type is 'none', set stress and strain to a zero matrix size dim x ne and return. 

> > ```
> >   * Consider looping through each dimension (defined in variable dim) to get each component of stress and strain. That way the code does not need to be hard-coded for 2D elements only.
> > ```
> 
> I wanted to avoid looping over dim so that I didn't re-calculate the stress at the same quadrature point 3 or 6 times. I have removed the 2D hard-coding by using tiered if-statements.
> 

Consider condensing this even further by storing the different components in the same matrix. 
* Lines 93-111: de = zeros(Mesh.nn, dim); ds = zeros(Mesh.nn, dim);
* Lines 184-204: de_e and ds_e defined similar to above
* Lines 240-264: for i = 1:dim; de_e(:,i) = N'*Quad.W(q)*dJe*strain_q(i); ds_e(:,i) = ... ; end
* Lines 280-299: de(enodes,:) = de(enodes,:) + de_e; (similar for ds)

**Comment by b3gee** [comment]
> 
> 
> > > ```
> > > * Notes on implementation:
> > >   
> > >   * The line `if ~strcmp(calc_type,'none')` removed all calculations of stresses at nodes. Consider maintaining this functionality (it should not be the default since it will not be output to VTK, but at least maintain it as an available option for debugging)
> > > ```
> > 
> > 
> > Previously, the stress calculation 'none' looped through all the elements and calculated stresses at all nodes in each element, then output none of them - which to me seems like a waste of computation power. Personally, I can't envision a situation in which I want to see the stress calculation for debugging, then not look at the plotted stress contours. My intuition as a user would be that 'none' prevents any stress calculations from taking place in order to increase the efficiency of the code.
> 
> I agree with what you're saying, so we're going to have to change the code a bit for this to make sense. Currently, the default output for getStrain is not of value, so I propose we make the default option 'center' (most efficient). We will need to change the header for getStrain and check setDefaults.m. Also in getStrain, change the default given if nargin < 4.
> 
> Then, I suggest we add an if statement at the start of getStrain. If calc_type is 'none', set stress and strain to a zero matrix size dim x ne and return.

Done.


> 
> > > ```
> > >   * Consider looping through each dimension (defined in variable dim) to get each component of stress and strain. That way the code does not need to be hard-coded for 2D elements only.
> > > ```
> > 
> > 
> > I wanted to avoid looping over dim so that I didn't re-calculate the stress at the same quadrature point 3 or 6 times. I have removed the 2D hard-coding by using tiered if-statements.
> 
> Consider condensing this even further by storing the different components in the same matrix.

I like this idea, it greatly condenses the code and removes the need to differentiate where the xy-term falls in 2D and 3D Voigt forms. Implemented.

**Comment by endrinar** [comment]
Nice, one last recommendation: 

Modify Lines 205-223 to a for loop:
```
for i = 1:dim
    de_e(:, i) = de_e(:,1) + N'*Quad.W(q)*dJe*strain_q(i);
    ds_e(:,i) = ....
end
```

And similarly for lines 258-277

**Comment by b3gee** [comment]
> 
> 
> Nice, one last recommendation:
> 
> Modify Lines 205-223 to a for loop:
> 
> ```
> for i = 1:dim
>     de_e(:, i) = de_e(:,1) + N'*Quad.W(q)*dJe*strain_q(i);
>     ds_e(:,i) = ....
> end
> ```
> 
> And similarly for lines 258-277

Done.

**Review by endrinar — APPROVED** [review]

**Pull request merged**
