### PR TITLE
Automate testing

### PR DESCRIPTION
**Pull request by b3gee**
- Created automated testing script with template to add more tests
- Currently only runs the Q4 plane stress manufactured solution test, as it is the only testing that has been merged into the development branch

### CODE REVIEW

**Comment by endrinar** [comment]
- [x] Reviewed function(s): RunTests, ManufacturedSolution, ManufacturedSolution_check 
- [x] Ran test case(s): RunTests
* Purpose of the code: to automate the test cases 
* Notes on implementation: 
   * It was smart to create a global variable for meshfilename and quadorder
   * Consider removing hardcoding of E and nu in ManufacturedSolution_check
   * Consider separating each test in RunTests.m to a separate function for readability
* Notes on legibility and style: 
   * RunTests header: uploaded by Bruce, so only need to acknowledge Saeed
* Notes on maintainability: N/A
* Suggested test cases: N/A

**Review by endrinar — CHANGES_REQUESTED** [review]
- [x] Reviewed function(s): RunTests, ManufacturedSolution, ManufacturedSolution_check 
- [x] Ran test case(s): RunTests
* Purpose of the code: to automate the test cases 
* Notes on implementation: 
   * It was smart to create a global variable for meshfilename and quadorder
   * Consider removing hardcoding of E and nu in ManufacturedSolution_check
   * Consider separating each test in RunTests.m to a separate function for readability
* Notes on legibility and style: 
   * RunTests header: uploaded by Bruce, so only need to acknowledge Saeed
* Notes on maintainability: N/A
* Suggested test cases: N/A

**Comment by shatefia** [comment]
Patch tests A, B, and C has been added to the Automate testing branch

**Comment by b3gee** [comment]
-Removed the hardcoding of E and nu in ManufacturedSolution
-Separated the running and checking of each individual test into separate scripts to improve legibility 
-Added summary of unit test results to RunTests
-Organized the Test Files folder into subfolders to prevent clutter

**Comment by b3gee** [comment]
- Merged develop into automate-testing branch to accommodate the changes from suppress-progresscomments. Fixed ensuing errors.
- Updated patch tests to include changes requested in the PatchTest branch.
- Removed hardcoding of PatchTest variables.

**Review by endrinar — CHANGES_REQUESTED** [review]
- [x] Reviewed function(s): RunTests, RunTest1-5, PatchTestA-C, PatchTest_check, ManufacturedSolution_check
- [x] Ran test case(s): RunTests
* Purpose of the code: Automate testing of code, patch tests, and manufactured solution
* Notes on implementation:
   * RunTests.m: 
      * There are some unused variables that need to be cleaned up: codeSubmitTime
      * Latest changes in the develop branch have changed some of the input in RunSim.m. These need to be incorporated into RunTests.m so that it runs properly. Remove Control.vtk. Change Control.vtk_dir to simply vtk_dir.
      * If you set the plot2vtk toggle on, there's an issue that the vtk files get deleted with each test, so at the end of the testing only the vtk files for the last test remain
   * RunTest1-5: 
      * no need to add function folder to the path again. already done in RunTests.m
      * some of the variables in the cleanup can be removed: curDir, VTKDirs, ConfigFiles, etc.
      * however, add the variable vtk_dir to the clean-up
   * PatchTest_check: 
      * can you explain why you selected the reaction error quantity to be the sum of external forces?
      * what is the difference between the norm function (used for the displacement error) and the manual calculation (used for the stress error)?
      * Consider replacing the error quantities with a norm, similar to the calculation you performed for manufacturedsolution_check.
   * Consider normalizing the error quantities with the exact solution
* Notes on legibility and style: 
   * Remove acknolwedgements on the files that you committed. We will use implicit acknolwedgements to keep most file headers short.
* Notes on maintainability: 
   * As we add more and more test cases we will need to create a naming convention so that it is easy to identify what each test does and which files are associated with it. Currently it is not easy to tell which config file and check file is associated with RunTest1.m, for example.
   * Great commit messages
   * Consider making a general function that computes error norms. I feel like it'll get used a lot. You would need to input the mesh and solution. One of the inputs can be an anonymous function for the exact solution (to keep it general). You may also consider providing the exact solution in the form of nodal values (in case someone uses a very fine mesh as the exact solution). 
* Suggested test cases: 
   * I suggest keeping the main patch tests with only 5-8 elements so that it is easy to debug when there is an error.

**Comment by endrinar** [comment]
I pushed some of the changes in RunSim.m and RunTest1-5 that I needed to run the file.

**Comment by SaeedHatefi** [comment]
- [ ] Reviewed function(s): RunTests, RunTest1-5, PatchTestA-C, PatchTest_check, ManufacturedSolution_check
 - [ ] Ran test case(s): RunTests

- Purpose of the code: to automate the test cases
              
- Notes on implementation:


  - RunTests.m:


     - For solving the issue that the vtk files get deleted with each test, it can be added vtk_dir before running each test case.

  - RunTest1-5:
     - It is correct. Function folder to the path can be deleted at RunTest1, RunTest2, RunTest3, RunTest4, RunTest5.

  -  PatchTest_check:
     - The sum of external forces is not the reaction error. In fact, it is for checking the equilibrium in x and y directions for patch tests. Fext_exact can be manually added to the code for the calculation of reaction error.
     - In matlab, norm function returns the Euclidean norm of the vectors. Stress and stress_exact are matrices. So, we cannot use norm function for them.

- Notes on legibility and style: N/A


- Notes on maintainability: N/A


- Suggested test cases: N/A

**Comment by b3gee** [comment]
> Notes on implementation:
> 
>     * RunTests.m:
>         * Latest changes in the develop branch have changed some of the input in RunSim.m. These need to be incorporated into RunTests.m so that it runs properly. Remove Control.vtk. Change Control.vtk_dir to simply vtk_dir.

**automate-testing** is up to date with **develop** and should now run properly even once merged.

>         * If you set the plot2vtk toggle on, there's an issue that the vtk files get deleted with each test, so at the end of the testing only the vtk files for the last test remain

I had originally anticipated that no vtk files would be output during the automated testing, as this would create unnecessary slow downs and an excessive number of files. The idea was that an individual failed test could be investigated using RunSim. The use of global variables for material parameters and mesh files has complicated this, so I have added the ability to save the VTK outputs by following Saeed's suggestion of adding a new vtk_dir to the start of each test.

>       * RunTest1-5:
>         
>         * no need to add function folder to the path again. already done in RunTests.m
Removed

>         * some of the variables in the cleanup can be removed: curDir, VTKDirs, ConfigFiles, etc.
>         * however, add the variable vtk_dir to the clean-up
cleanup has been cleaned up

>       * PatchTest_check:
>         
>         * can you explain why you selected the reaction error quantity to be the sum of external forces?
Saeed's original check function hard-coded the nodal forces and checked that the external forces returned by the code matched the hard-coded external forces. I don't think this approach works as well once I generalized the PatchTests to work for arbitrary meshes and tractions. It would require an automated calculation of the nodal forces, which would just be a repetition of the calculation performed in prescribing the nodal forces in PatchTestC. We would be using the same code to check that the code we used to prescribe the nodal forces does indeed match - which I don't think provides much insight. So instead, I chose to check that the sum of the external and reaction forces is 0 so that equilibrium is satisfied.

>         * what is the difference between the norm function (used for the displacement error) and the manual calculation (used for the stress error)?
As Saeed stated, the norm function can only be used for vectors. The stress matrix is a 3xn matrix of nodal Voigt form stresses, so the norm function doesn't work. The manual calculation performs an equivalent matrix operation to the norm function.

>         * Consider replacing the error quantities with a norm, similar to the calculation you performed for manufacturedsolution_check.
>       * Consider normalizing the error quantities with the exact solution

Calculating the error norm should not be necessary for the patch test, as the FEA code should produce exactly reproduce the linear stress field. Therefore the error norm should be 0, and if the nodal values should be exact.

> 
>     * Notes on legibility and style:
>       
>       * Remove acknolwedgements on the files that you committed. We will use implicit acknolwedgements to keep most file headers short.
Removed.

> 
>     * Notes on maintainability:
>       
>       * As we add more and more test cases we will need to create a naming convention so that it is easy to identify what each test does and which files are associated with it. Currently it is not easy to tell which config file and check file is associated with RunTest1.m, for example.

I would note that it is easy to find the associated config files and check files by opening RunTest1.m. The naming conventions of RunTestX.m could be more descriptive though. Maybe something like:
RunT1_PatchTestA.m
RunT5_ManSolQ9.m

>       * Consider making a general function that computes error norms. I feel like it'll get used a lot. You would need to input the mesh and solution. One of the inputs can be an anonymous function for the exact solution (to keep it general). You may also consider providing the exact solution in the form of nodal values (in case someone uses a very fine mesh as the exact solution).

Agreed. I propose we open this as an issue and refactor the code later, rather than confuse the current branch with too many more new functions.

> 
>     * Suggested test cases:
>       
>       * I suggest keeping the main patch tests with only 5-8 elements so that it is easy to debug when there is an error.

I have reduced the number of elements in the patch test.

**Comment by endrinar** [comment]
> > Notes on implementation:
> > ```
> > * RunTests.m:
> >     * Latest changes in the develop branch have changed some of the input in RunSim.m. These need to be incorporated into RunTests.m so that it runs properly. Remove Control.vtk. Change Control.vtk_dir to simply vtk_dir.
> > ```
> 
> **automate-testing** is up to date with **develop** and should now run properly even once merged.
> 
:+1:
> > ```
> >     * If you set the plot2vtk toggle on, there's an issue that the vtk files get deleted with each test, so at the end of the testing only the vtk files for the last test remain
> > ```
> 
> I had originally anticipated that no vtk files would be output during the automated testing, as this would create unnecessary slow downs and an excessive number of files. The idea was that an individual failed test could be investigated using RunSim. The use of global variables for material parameters and mesh files has complicated this, so I have added the ability to save the VTK outputs by following Saeed's suggestion of adding a new vtk_dir to the start of each test.
> 
I agree that most of the time we won't want to generate VTK files for the testing, but it may be convenient to do so sometimes during debugging. I like that you've added the ability to do so. 
> > ```
> >   * RunTest1-5:
> >     
> >     * no need to add function folder to the path again. already done in RunTests.m
> > ```
> 
> Removed
> 
:+1:
> > ```
> >     * some of the variables in the cleanup can be removed: curDir, VTKDirs, ConfigFiles, etc.
> >     * however, add the variable vtk_dir to the clean-up
> > ```
> 
> cleanup has been cleaned up
> 
:+1:
> > ```
> >   * PatchTest_check:
> >     
> >     * can you explain why you selected the reaction error quantity to be the sum of external forces?
> > ```
> 
> Saeed's original check function hard-coded the nodal forces and checked that the external forces returned by the code matched the hard-coded external forces. I don't think this approach works as well once I generalized the PatchTests to work for arbitrary meshes and tractions. It would require an automated calculation of the nodal forces, which would just be a repetition of the calculation performed in prescribing the nodal forces in PatchTestC. We would be using the same code to check that the code we used to prescribe the nodal forces does indeed match - which I don't think provides much insight. So instead, I chose to check that the sum of the external and reaction forces is 0 so that equilibrium is satisfied.
> 
:+1:
> > ```
> >     * what is the difference between the norm function (used for the displacement error) and the manual calculation (used for the stress error)?
> > ```
> 
> As Saeed stated, the norm function can only be used for vectors. The stress matrix is a 3xn matrix of nodal Voigt form stresses, so the norm function doesn't work. The manual calculation performs an equivalent matrix operation to the norm function.
> 
:+1:
> > ```
> >     * Consider replacing the error quantities with a norm, similar to the calculation you performed for manufacturedsolution_check.
> >   * Consider normalizing the error quantities with the exact solution
> > ```
> 
> Calculating the error norm should not be necessary for the patch test, as the FEA code should produce exactly reproduce the linear stress field. Therefore the error norm should be 0, and if the nodal values should be exact.
> 
:+1:
> > ```
> > * Notes on legibility and style:
> >   
> >   * Remove acknolwedgements on the files that you committed. We will use implicit acknolwedgements to keep most file headers short.
> > ```
> 
> Removed.
> 
:+1:
> > ```
> > * Notes on maintainability:
> >   
> >   * As we add more and more test cases we will need to create a naming convention so that it is easy to identify what each test does and which files are associated with it. Currently it is not easy to tell which config file and check file is associated with RunTest1.m, for example.
> > ```
> 
> I would note that it is easy to find the associated config files and check files by opening RunTest1.m. The naming conventions of RunTestX.m could be more descriptive though. Maybe something like:
> RunT1_PatchTestA.m
> RunT5_ManSolQ9.m
> 
This is good, it's easier to associate them now. We will continue to think about how we name tests and models in the future. 
> > ```
> >   * Consider making a general function that computes error norms. I feel like it'll get used a lot. You would need to input the mesh and solution. One of the inputs can be an anonymous function for the exact solution (to keep it general). You may also consider providing the exact solution in the form of nodal values (in case someone uses a very fine mesh as the exact solution).
> > ```
> 
> Agreed. I propose we open this as an issue and refactor the code later, rather than confuse the current branch with too many more new functions.
> 
:+1:
> > ```
> > * Suggested test cases:
> >   
> >   * I suggest keeping the main patch tests with only 5-8 elements so that it is easy to debug when there is an error.
> > ```
> 
> I have reduced the number of elements in the patch test.

:+1:


Review complete, I will merge and close the branch now.

**Review by endrinar — APPROVED** [review]

**Pull request merged**
